CREATE USER ${DSTDB_ARC_USER}; -- PASSWORD 'password';
ALTER USER ${DSTDB_ARC_USER} CREATEDB;
-- ALTER ROLE arcdst WITH REPLICATION;
-- create database root;
CREATE DATABASE ${DSTDB_DB} WITH OWNER ${DSTDB_ARC_USER}; -- ENCODING 'UTF8';
-- CREATE DATABASE io WITH OWNER arcdst; -- ENCODING 'UTF8';
