CREATE USER arcsrcl; -- PASSWORD 'password';
ALTER USER arcsrc CREATEDB;
-- ALTER ROLE arcsrc WITH REPLICATION;
CREATE DATABASE arcsrc WITH OWNER arcsrcl; -- ENCODING 'UTF8';
CREATE DATABASE io WITH OWNER arcsrcl; -- ENCODING 'UTF8';