-- II. Set up Oracle User

CREATE USER ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER} IDENTIFIED BY ${DSTDB_ARC_PW};

ALTER USER ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER} quota unlimited on USERS;

GRANT CREATE SESSION TO ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER};

GRANT CREATE ANY DIRECTORY TO ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER};

GRANT
    SELECT ANY TABLE,
    INSERT ANY TABLE,
    UPDATE ANY TABLE,
    DELETE ANY TABLE,
    CREATE ANY TABLE,
    ALTER ANY TABLE,
    DROP ANY TABLE
    TO ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER};

GRANT
    CREATE ANY SEQUENCE,
    SELECT ANY SEQUENCE,
    CREATE ANY INDEX
    TO ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER};

GRANT SET CONTAINER TO  ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER} CONTAINER=ALL;

GRANT SELECT ON DBA_PDBS to ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER} CONTAINER=ALL;

-- required even non CDC
GRANT SELECT ON gv_\$instance TO ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER};
