-- II. Set up Oracle User

CREATE USER ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER} IDENTIFIED BY ${SRCDB_ARC_PW};

ALTER USER ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER} default tablespace USERS;

ALTER USER ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER} quota unlimited on USERS;

GRANT CREATE SESSION TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};

GRANT
    SELECT ANY TABLE,
    INSERT ANY TABLE,
    UPDATE ANY TABLE,
    DELETE ANY TABLE,
    CREATE ANY TABLE,
    ALTER ANY TABLE,
    DROP ANY TABLE
    TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};

GRANT
    CREATE ANY SEQUENCE,
    SELECT ANY SEQUENCE,
    CREATE ANY INDEX
    TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};

GRANT SET CONTAINER TO  ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER} CONTAINER=ALL;

GRANT SELECT ON DBA_PDBS to ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER} CONTAINER=ALL;

-- required even non CDC
GRANT SELECT ON gv_\$instance TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};

-- 3 CDC

GRANT EXECUTE_CATALOG_ROLE TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT LOGMINING TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};


GRANT SELECT ON v_\$logmnr_contents TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON gv_\$archived_log TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON gv_\$logfile TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
-- below Oracle 19c
GRANT SELECT ON v_\$logfile TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};

-- Enable logs on database
-- https://docs.arcion.io/docs/source-setup/oracle/setup-guide/oracle-traditional-database/#enable-logs
-- not having this will result in
-- CDC not enabled
ALTER DATABASE FORCE LOGGING;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
--

GRANT CREATE SESSION TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ANY TABLE TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};

GRANT SELECT ON gv_\$instance TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON gv_\$PDBS TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON gv_\$log TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON gv_\$database_incarnation to ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};

-- 4 setup global permissions
-- https://docs.arcion.io/docs/source-setup/oracle/setup-guide/oracle-traditional-database/#iv-set-up-global-permissions

-- onetime
GRANT SELECT ON DBA_SEGMENTS TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};

-- snapshot and CDC
GRANT SELECT ON gv_\$database TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON gv_\$transaction TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
--Not required for replicant release 20.8.13.7 and above
GRANT SELECT ON gv_\$session TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};

-- CDC
GRANT FLASHBACK ANY TABLE TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};

-- schema migration
GRANT SELECT ON ALL_TABLES TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON ALL_VIEWS TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON ALL_CONSTRAINTS TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON ALL_CONS_COLUMNS TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON ALL_PART_TABLES TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON ALL_PART_KEY_COLUMNS TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON ALL_TAB_COLUMNS TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON SYS.ALL_INDEXES TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON SYS.ALL_IND_COLUMNS TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON SYS.ALL_IND_EXPRESSIONS TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};

-- native log reader
GRANT SELECT ON gv_\$instance TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON v_\$log TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON v_\$logfile TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON v_\$archived_log to ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON dba_objects TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON v_\$transportable_platform TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};

-- missing in the docs
-- native log reader
GRANT SELECT ON V_$DATABSSE TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};

-- missing in the docs
-- GIANT HACK as there are others missing as well
 grant dba to  ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};

GRANT CREATE SESSION TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT EXECUTE_CATALOG_ROLE TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ANY TABLE TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON all_constraints TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON all_cons_columns TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON all_indexes TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON all_ind_expressions TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON all_part_tables TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON all_part_key_columns TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON all_tables TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON all_tab_columns TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON all_views TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON dba_constraints TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON dba_cons_columns TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON dba_indexes TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON dba_ind_columns TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON dba_lobs TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON dba_objects TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON dba_roles TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON dba_tables TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON dba_tab_cols TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON gv_\$database TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON gv_\$instance TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON gv_\$transaction TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON v_\$archived_log to ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON v_\$database TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON v_\$log TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON v_\$logfile TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};
GRANT SELECT ON v_\$transportable_platform TO ${SRCDB_USER_PREFIX}${SRCDB_ARC_USER};