-- II. Set up Oracle User

CREATE USER ${SRCDB_ARC_USER} IDENTIFIED BY ${SRCDB_ARC_PW};

ALTER USER ${SRCDB_ARC_USER} quota unlimited on USERS;

GRANT CREATE SESSION TO ${SRCDB_ARC_USER};

GRANT
    SELECT ANY TABLE,
    INSERT ANY TABLE,
    UPDATE ANY TABLE,
    DELETE ANY TABLE,
    CREATE ANY TABLE,
    ALTER ANY TABLE,
    DROP ANY TABLE
    TO ${SRCDB_ARC_USER};

GRANT
    CREATE ANY SEQUENCE,
    SELECT ANY SEQUENCE,
    CREATE ANY INDEX
    TO ${SRCDB_ARC_USER};

GRANT SET CONTAINER TO  ${SRCDB_ARC_USER} CONTAINER=ALL;

GRANT SELECT ON DBA_PDBS to ${SRCDB_ARC_USER} CONTAINER=ALL;

-- required even non CDC
GRANT SELECT ON gv_\$instance TO ${SRCDB_ARC_USER};

-- onetime
GRANT SELECT ON DBA_SEGMENTS TO ${SRCDB_ARC_USER};

-- snapshot and CDC
GRANT SELECT ON gv_\$database TO ${SRCDB_ARC_USER};
GRANT SELECT ON gv_\$transaction TO ${SRCDB_ARC_USER};
--Not required for replicant release 20.8.13.7 and above
GRANT SELECT ON gv_\$session TO ${SRCDB_ARC_USER};

