-- 3 CDC

GRANT EXECUTE_CATALOG_ROLE TO ${SRCDB_ARC_USER};
GRANT LOGMINING TO ${SRCDB_ARC_USER};


GRANT SELECT ON v_\$logmnr_contents TO ${SRCDB_ARC_USER};
GRANT SELECT ON gv_\$archived_log TO ${SRCDB_ARC_USER};
GRANT SELECT ON gv_\$logfile TO ${SRCDB_ARC_USER};
-- below Oracle 19c
GRANT SELECT ON v_\$logfile TO ${SRCDB_ARC_USER};

-- Enable logs on database
-- https://docs.arcion.io/docs/source-setup/oracle/setup-guide/oracle-traditional-database/#enable-logs
-- not having this will result in
-- CDC not enabled
ALTER DATABASE FORCE LOGGING;
ALTER SYSTEM SWITCH LOGFILE;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
--

GRANT CREATE SESSION TO ${SRCDB_ARC_USER};
GRANT SELECT ANY TABLE TO ${SRCDB_ARC_USER};

GRANT SELECT ON gv_\$instance TO ${SRCDB_ARC_USER};
GRANT SELECT ON gv_\$PDBS TO ${SRCDB_ARC_USER};
GRANT SELECT ON gv_\$log TO ${SRCDB_ARC_USER};
GRANT SELECT ON gv_\$database_incarnation to ${SRCDB_ARC_USER};

-- 4 setup global permissions
-- https://docs.arcion.io/docs/source-setup/oracle/setup-guide/oracle-traditional-database/#iv-set-up-global-permissions

-- onetime
GRANT SELECT ON DBA_SEGMENTS TO ${SRCDB_ARC_USER};

-- snapshot and CDC
GRANT SELECT ON gv_\$database TO ${SRCDB_ARC_USER};
GRANT SELECT ON gv_\$transaction TO ${SRCDB_ARC_USER};
--Not required for replicant release 20.8.13.7 and above
GRANT SELECT ON gv_\$session TO ${SRCDB_ARC_USER};

-- CDC
GRANT FLASHBACK ANY TABLE TO ${SRCDB_ARC_USER};

-- schema migration
GRANT SELECT ON ALL_TABLES TO ${SRCDB_ARC_USER};
GRANT SELECT ON ALL_VIEWS TO ${SRCDB_ARC_USER};
GRANT SELECT ON ALL_CONSTRAINTS TO ${SRCDB_ARC_USER};
GRANT SELECT ON ALL_CONS_COLUMNS TO ${SRCDB_ARC_USER};
GRANT SELECT ON ALL_PART_TABLES TO ${SRCDB_ARC_USER};
GRANT SELECT ON ALL_PART_KEY_COLUMNS TO ${SRCDB_ARC_USER};
GRANT SELECT ON ALL_TAB_COLUMNS TO ${SRCDB_ARC_USER};
GRANT SELECT ON SYS.ALL_INDEXES TO ${SRCDB_ARC_USER};
GRANT SELECT ON SYS.ALL_IND_COLUMNS TO ${SRCDB_ARC_USER};
GRANT SELECT ON SYS.ALL_IND_EXPRESSIONS TO ${SRCDB_ARC_USER};

