#!/usr/bin/env bash 

export_env() {
local TMPINI="${1:-/tmp/ini_menu.sh}"    
local CFGINI="${2:-$CFG_DIR}"

cat >$TMPINI <<EOF
# source
export SRCDB_DIR=${SRCDB_DIR}
export SRCDB_TYPE=${SRCDB_TYPE}
export SRCDB_HOST=${SRCDB_HOST}
export SRCDB_GRP=${SRCDB_GRP}
export SRCDB_PORT=${SRCDB_PORT}
# destination
export DSTDB_DIR=${DSTDB_DIR}
export DSTDB_TYPE=${DSTDB_TYPE}
export DSTDB_HOST=${DSTDB_HOST}
export DSTDB_GRP=${DSTDB_GRP}
export DSTDB_PORT=${DSTDB_PORT}
# replication
export REPL_TYPE=${REPL_TYPE}
export ARCION_ARGS="${ARCION_ARGS}"
# root id/password
export SRCDB_ROOT=${SRCDB_ROOT}
export SRCDB_PW=${SRCDB_PW}
export DSTDB_ROOT=${DSTDB_ROOT}
export DSTDB_PW=${DSTDB_PW}
# user id/password
export SRCDB_ARC_USER=${SRCDB_ARC_USER}
export SRCDB_ARC_PW=${SRCDB_ARC_PW}
export DSTDB_ARC_USER=${DSTDB_ARC_USER}
export DSTDB_ARC_PW=${DSTDB_ARC_PW}
# cfg
export CFG_DIR=${CFG_DIR}
export LOG_ID=${LOG_ID}
# JDBC
export SRCDB_JDBC_DRIVER="$SRCDB_JDBC_DRIVER"
export SRCDB_JDBC_URL="$SRCDB_JDBC_URL"
export SRCDB_JDBC_URL_IDPW="$SRCDB_JDBC_URL_IDPW"
export SRCDB_ROOT_URL="$SRCDB_ROOT_URL"
export DSTDB_JDBC_DRIVER="$DSTDB_JDBC_DRIVER"
export DSTDB_JDBC_URL="$DSTDB_JDBC_URL"
export DSTDB_JDBC_URL_IDPW="$DSTDB_JDBC_URL_IDPW"
export DSTDB_ROOT_URL="$DSTDB_ROOT_URL"
# JSQSH
export SRCDB_JSQSH_DRIVER="$SRCDB_JSQSH_DRIVER"
export DSTDB_JSQSH_DRIVER="$DSTDB_JSQSH_DRIVER"
# YCSB
export SRCDB_YCSB_DRIVER="$SRCDB_YCSB_DRIVER"
export DSTDB_YCSB_DRIVER="$DSTDB_YCSB_DRIVER"
# SCHEMA
export SRCDB_SCHEMA=${SRCDB_SCHEMA}
export SRCDB_COMMA_SCHEMA=${SRCDB_COMMA_SCHEMA}
export DSTDB_SCHEMA=${DSTDB_SCHEMA}
export DSTDB_COMMA_SCHEMA=${DSTDB_COMMA_SCHEMA}
# THREADS
export SRCDB_SNAPSHOT_THREADS=${SRCDB_SNAPSHOT_THREADS}
export SRCDB_REALTIME_THREADS=${SRCDB_REALTIME_THREADS}
export SRCDB_DELTA_SNAPSHOT_THREADS=${SRCDB_DELTA_SNAPSHOT_THREADS}
export DSTDB_SNAPSHOT_THREADS=${DSTDB_SNAPSHOT_THREADS}
export DSTDB_REALTIME_THREADS=${DSTDB_REALTIME_THREADS}
# workload control
export max_cpus="$max_cpus"
export workload_rate="$workload_rate"
export workload_threads="$workload_threads"
export workload_timer="$workload_timer"
export workload_size_factor="$workload_size_factor"
EOF
cp $TMPINI $CFGINI/.
}
