CREATE USER ${DSTDB_ARC_USER} PASSWORD '${DSTDB_ARC_PW}';
ALTER USER ${DSTDB_ARC_USER} CREATEDB;
ALTER ROLE ${DSTDB_ARC_USER} WITH REPLICATION;
CREATE DATABASE ${DSTDB_ARC_USER} WITH OWNER ${DSTDB_ARC_USER} ENCODING 'UTF8';