CREATE USER ${DSTDB_ARC_USER} PASSWORD '${DSTDB_ARC_PW}';
ALTER USER ${DSTDB_ARC_USER} CREATEDB;
create database ${DSTDB_ARC_USER};
grant all privileges on database ${DSTDB_ARC_USER} to ${DSTDB_ARC_USER};
