CREATE USER ${SRCDB_ARC_USER} PASSWORD '${SRCDB_ARC_PW}';
ALTER USER ${SRCDB_ARC_USER} CREATEDB;
ALTER ROLE ${SRCDB_ARC_USER} WITH REPLICATION;
create database ${SRCDB_ARC_USER};
grant all privileges on database ${SRCDB_ARC_USER} to ${SRCDB_ARC_USER};

