FROM arcionlabs/replicant-on-premises:latest

# To create an image
#   docker buildx build --push --platform=linux/amd64,linux/arm64/v8 -t robertslee/arcion -f Dockerfile.arcion .

# RUN amazon-linux-extras install java-openjdk11
# RUN alternatives --set java java-11-openjdk.x86_64