CREATE LOGIN ${DSTDB_ARC_USER} WITH PASSWORD = '${DSTDB_ARC_PW}';
create database ${DSTDB_ARC_USER};
use ${DSTDB_ARC_USER};
CREATE USER ${DSTDB_ARC_USER} FOR LOGIN ${DSTDB_ARC_USER} WITH DEFAULT_SCHEMA=dbo;
ALTER ROLE db_owner ADD MEMBER ${DSTDB_ARC_USER};
ALTER ROLE db_ddladmin ADD MEMBER ${DSTDB_ARC_USER};
alter user ${DSTDB_ARC_USER} with default_schema=dbo;
ALTER LOGIN ${DSTDB_ARC_USER} WITH DEFAULT_DATABASE=[${DSTDB_ARC_USER}];