CREATE LOGIN ${SRCDB_ARC_USER} WITH PASSWORD = '${SRCDB_ARC_PW}';
create database ${SRCDB_DB};
use ${SRCDB_ARC_USER};
CREATE USER ${SRCDB_ARC_USER} FOR LOGIN ${SRCDB_ARC_USER} WITH DEFAULT_SCHEMA=dbo;
ALTER ROLE db_owner ADD MEMBER ${SRCDB_ARC_USER};
ALTER ROLE db_ddladmin ADD MEMBER ${SRCDB_ARC_USER};
alter user ${SRCDB_ARC_USER} with default_schema=dbo;
ALTER LOGIN ${SRCDB_ARC_USER} WITH DEFAULT_DATABASE=[${SRCDB_DB}];


