CREATE USER ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER} IDENTIFIED BY ${DSTDB_ARC_PW};

grant CREATE SESSION to ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER};
grant ALTER SESSION to ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER}; 
grant CREATE DATABASE LINK  to ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER}; 
grant CREATE MATERIALIZED VIEW  to ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER}; 
grant CREATE TABLE  to ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER};
grant CREATE SCHEMA  to ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER};

GRANT CREATE ANY DIRECTORY TO ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER};
-- If you are unable to provide the permission above, you must manually create the following directories:
CREATE OR REPLACE DIRECTORY csv_data_dir AS '/data/shared_fs';
CREATE OR REPLACE DIRECTORY csv_log_dir AS '/data/shared_fs';

-- GRANT ALTER TABLE TO ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER};

-- grant CREATE PROCEDURE  to ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER};

grant CREATE PUBLIC SYNONYM  to ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER}; 
grant CREATE ROLE  to ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER};
grant CREATE SEQUENCE  to ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER}; 
grant CREATE SYNONYM  to ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER}; 
grant CREATE TYPE  to ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER}; 
grant CREATE VIEW  to ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER}; 
grant UNLIMITED TABLESPACE to ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER};

grant CREATE TRIGGER  to ${DSTDB_USER_PREFIX}${DSTDB_ARC_USER}
go
