alter session set "_ORACLE_SCRIPT"=true;

CREATE USER ${SRCDB_ARC_USER} IDENTIFIED BY ${SRCDB_ARC_PW};

grant CREATE SESSION, ALTER SESSION, CREATE DATABASE LINK, CREATE MATERIALIZED VIEW, CREATE PROCEDURE, CREATE PUBLIC SYNONYM, CREATE ROLE, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, CREATE TRIGGER, CREATE TYPE, CREATE VIEW, UNLIMITED TABLESPACE to ${SRCDB_ARC_USER};

ALTER SESSION SET container=xepdb1;

CREATE PLUGGABLE DATABASE ${SRCDB_DB};
