CREATE USER ${ORA_USER_PREFIX}${SRCDB_ARC_USER} IDENTIFIED BY ${SRCDB_ARC_PW};

grant CREATE SESSION to ${ORA_USER_PREFIX}${SRCDB_ARC_USER};

grant ALTER SESSION to ${ORA_USER_PREFIX}${SRCDB_ARC_USER}; 
grant CREATE DATABASE LINK  to ${ORA_USER_PREFIX}${SRCDB_ARC_USER}; 
grant CREATE MATERIALIZED VIEW  to ${ORA_USER_PREFIX}${SRCDB_ARC_USER}; 

grant CREATE TABLE  to ${ORA_USER_PREFIX}${SRCDB_ARC_USER};
grant CREATE SCHEMA  to ${ORA_USER_PREFIX}${SRCDB_ARC_USER};

GRANT CREATE ANY DIRECTORY TO ${ORA_USER_PREFIX}${SRCDB_ARC_USER};
--If you are unable to provide the permission above, you must manually create the following directories:
CREATE OR REPLACE DIRECTORY csv_data_dir AS '/data/shared_fs';
CREATE OR REPLACE DIRECTORY csv_log_dir AS '/data/shared_fs';

GRANT ALTER TABLE TO ${ORA_USER_PREFIX}${SRCDB_ARC_USER};

-- grant CREATE PROCEDURE  to ${ORA_USER_PREFIX}${SRCDB_ARC_USER};
grant CREATE PUBLIC SYNONYM  to ${ORA_USER_PREFIX}${SRCDB_ARC_USER}; 
grant CREATE ROLE  to ${ORA_USER_PREFIX}${SRCDB_ARC_USER};
grant CREATE SEQUENCE  to ${ORA_USER_PREFIX}${SRCDB_ARC_USER}; 
grant CREATE SYNONYM  to ${ORA_USER_PREFIX}${SRCDB_ARC_USER}; 
grant CREATE TRIGGER  to ${ORA_USER_PREFIX}${SRCDB_ARC_USER}; 
grant CREATE TYPE  to ${ORA_USER_PREFIX}${SRCDB_ARC_USER}; 
grant CREATE VIEW  to ${ORA_USER_PREFIX}${SRCDB_ARC_USER}; 
grant UNLIMITED TABLESPACE to ${ORA_USER_PREFIX}${SRCDB_ARC_USER};
